AgrimoduleSoftware/ASS/ass/solarvibes/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, IntegerField
from wtforms.fields.html5 import DateField
from wtforms.validators import Email, Length, NumberRange
from flask_uploads import IMAGES


# Constructor
class PreUserProfileForm:
    def __init__(self, username, name, last_name, address, zipcode, city, state, country, email, email_rec, birthday, image, mobile):
        self.username    = username
        self.name        = name
        self.last_name   = last_name
        self.address     = address
        self.zipcode     = zipcode
        self.city        = city
        self.state       = state
        self.country     = country
        self.email       = email
        self.email_rec   = email_rec
        self.birthday    = birthday
        self.image       = image
        self.mobile      = mobile

class UserProfileForm(FlaskForm):
    username    = StringField('Username',           validators=[Length(min=2, max=30, message='Your Username needs to be at least 2 characters long.')])
    name        = StringField('Name',               validators=[Length(min=2, max=30, message='Your name needs to be at least 2 characters long.')])
    last_name   = StringField('Last name',          validators=[Length(min=2, max=30, message='Your last name needs to be at least 2 characters long.')])
    address     = StringField('Address',            validators=[Length(min=2, max=30, message='Minimum: 2 characters.')])
    zipcode     = IntegerField('Zipcode',            validators=[NumberRange(min=1, max=99999, message='Number of your code')])
    city        = StringField('City',               validators=[Length(min=2, max=30, message='Minimum: 2 characters.')])
    state       = StringField('State',              validators=[Length(min=2, max=30, message='Minimum: 2 characters.')])
    country     = StringField('Country',            validators=[Length(min=2, max=30, message='Minimum: 2 characters.')])
    email       = StringField('Email',              validators=[Length(min=5, max=30, message=None), Email()])
    email_rec   = StringField('Recovery Email',     validators=[Length(min=5, max=30, message=None), Email()])
    birthday    = DateField('Birthday',             format='%d %B, %Y')
    image       = FileField(                        validators=[FileAllowed(IMAGES, 'Only images allowed.')])
    mobile      = StringField('Mobile',             validators=[Length(min=7, max=30, message=None)])

AgrimoduleSoftware/ASS/ass/solarvibes/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from solarvibes import db, photos
from solarvibes.users.forms import UserProfileForm, PreUserProfileForm # User Forms
from solarvibes.models import User
from flask_login import current_user
from flask_security import login_required

users = Blueprint(
    'users',
    __name__,
    template_folder="templates",
)

##################
# USER PROFILE
##################
@users.route('/', methods=['GET', 'POST'])
@login_required
def profile():
    name = current_user.name
    return render_template('users/profile.html', name=name)

##################
# USER PROFILE EDIT
##################
@users.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    user = User.query.filter_by(email=current_user.email).first()
    # Prepopulate form
    myUser = PreUserProfileForm(username = user.username,
                                name = user.name,
                                last_name = user.last_name,
                                address = user.address,
                                zipcode = user.zipcode,
                                city = user.city,
                                state = user.state,
                                country = user.country,
                                email = user.email,
                                email_rec = user.email_rec,
                                birthday = user.birthday,
                                image = user.image,
                                mobile = user.mobile)
    form = UserProfileForm(obj=myUser)
    # if image is not uploaded it gets a TypeError
    if form.validate_on_submit():   # IF request.methiod == 'POST'
        user = User.query.filter_by(id=current_user.get_id()).first()
        # FIELD OBJS  TO DB
        try:
            # IMAGE HANDLING
            if not form.image.data == user.image:
                image_filename = photos.save(form.image.data)
                image_url = photos.url(image_filename)
                user.image = image_url
            # REST OF FORM HANDLING
            user.username = form.username.data
            user.name = form.name.data
            user.last_name = form.last_name.data
            user.address = form.address.data
            user.zipcode = form.zipcode.data
            user.city = form.city.data
            user.state = form.state.data
            user.country = form.country.data
            user.email = form.email.data
            user.email_rec = form.email_rec.data
            user.birthday = form.birthday.data
            user.mobile = form.mobile.data
            db.session.commit()
        except Exception as e:
            flash(e)
            print(e)
            db.session.rollback()
        flash('You updated sucessfully your profile')
        return redirect(url_for('users.profile'))
    return render_template('users/edit_profile.html', form=form)

AgrimoduleSoftware/ASS/ass/solarvibes/users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
Edit profile
{% endblock %}

{% block content %}
<div class="container">
    <h4>Farmer Information</h4>
    <!-- FIRST FORM -->
    <form method="POST" action="{{ url_for('users.edit_profile') }}" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div>
            <h5>{{ form.name.data }} {{ form.last_name.data }}</h5>
        </div>
        <!-- Image -->
        <div class="row">
            <div class="col s12">
                <!-- User Image -->
                {% if current_user.image == None %}
                <img src="{{ url_for('static', filename='images/favicon.png') }}" alt="Solarvibes logo" width="100px" height="auto">
                {% else %}
                <img src="{{ current_user.image }}"  alt="Profile Picture" class="img-responsive" width="100px" height="100">
                {% endif %}
            </div>
        </div>
        <br>



        <div class="row">
            <div class="col s12 m6">
                {{ render_field_with_errors(form.username) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.name) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.last_name) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.email) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.mobile) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.email_rec) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.birthday, class='datepicker') }}
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                {{ render_field_with_errors(form.address) }}
            </div>
        </div>
        <div class="row">
            <div class="col s4">
                {{ render_field_with_errors(form.city) }}
            </div>
            <div class="col s2">
                {{ render_field_with_errors(form.zipcode) }}
            </div>
            <div class="col s2">
                {{ render_field_with_errors(form.state) }}
            </div>
            <div class="col s4">
                {{ render_field_with_errors(form.country) }}
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                {{ form.image }}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col s6">
                <input type="submit" class="btn waves-effect waves-light" value="Save">
            </div>
            <div class="col s6">
                <a href="{{ url_for('users.profile') }}" class="btn waves-effect waves-light">Cancel</a>
            </div>
        </div>
    </form>

    <br>
    <br>

    {#
    {% if current_user.is_authenticated: %}
    <div class="collection black-text">
        <a href="{{ url_for('users.profile') }}" class="collection-item grey-text">Home
            <div class="secondary-content"><i class="material-icons svgreen-text">home</i></div>
        </a>
    </div>
    {% endif %}
    #}

</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
	Profile
{% endblock %}

{% block user_profile_active %}
active
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Profile</h1>
	<div class="collection black-text">
		{# <a href="{{ url_for('main.index') }}" class="collection-item grey-text"Home
			<div class="secondary-content"><i class="fab fa-facebook-f"></i></div>
		</a> #}
		{# <a href="{{ url_for('user_weather') }}" class="collection-item grey-text">Weather
			<div class="secondary-content"><i class="fab fa-facebook-f"></i></div>
		</a> #}
	</div>

	<div class="collection black-text">
		<a href="{{ url_for('users.edit_profile') }}" class="collection-item grey-text">Edit profile
			<div class="secondary-content"><i class="fab fa-facebook-f"></i></div>
		</a>
	</div>

</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
Edit profile
{% endblock %}

{% block content %}
<div class="container">
    <h4>Farmer Information</h4>
    <!-- FIRST FORM -->
    <form method="POST" action="{{ url_for('users.profile_edit') }}" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div>
            <h5>{{ form.name.data }} {{ form.last_name.data }}</h5>
        </div>
        <!-- Image -->
        <div class="row">
            <div class="col s12">
                <!-- User Image -->
                {% if current_user.image == None %}
                <img src="{{ url_for('users.static', filename='images/favicon.png') }}" alt="Solarvibes logo" width="100%" height="auto">
                {% else %}
                <img src="{{ current_user.image }}"  alt="Profile Picture" class="img-responsive" width="100" height="100">
                {% endif %}
            </div>
            <div class="col s12">
                {{ form.image }}
            </div>
        </div>
        <br>



        <div class="row">
            <div class="col s12 m6">
                {{ render_field_with_errors(form.username) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.name) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.last_name) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.email) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.mobile) }}
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                {{ render_field_with_errors(form.email_rec) }}
            </div>
            <div class="col s6">
                {{ render_field_with_errors(form.birthday, class="datepicker") }}
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                {{ render_field_with_errors(form.address) }}
            </div>
        </div>
        <div class="row">
            <div class="col s4">
                {{ render_field_with_errors(form.city) }}
            </div>
            <div class="col s2">
                {{ render_field_with_errors(form.zipcode) }}
            </div>
            <div class="col s2">
                {{ render_field_with_errors(form.state) }}
            </div>
            <div class="col s4">
                {{ render_field_with_errors(form.country) }}
            </div>
        </div>


        <div>
            <input type="submit" class="btn waves-effect waves-light" value="Save">
        </div>
    </form>


    {#
    {% if current_user.is_authenticated: %}
    <br><br>
    <div class="collection black-text">
        <a href="{{ url_for('home') }}" class="collection-item grey-text">Home
            <div class="secondary-content"><i class="material-icons svgreen-text">home</i></div>
        </a>
    </div>
    {% endif %}
    #}

</div>
{% endblock %}