AgrimoduleSoftware/ASS/ass/solarvibes/agrimodule/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from solarvibes.models import User, Agrimodule, Measurement, Agrisensor, Field
from flask_login import current_user
from flask_security import login_required

agrimodule_bp = Blueprint(
    'agrimodule_bp',
    __name__,
    template_folder="templates"
)


##################
# USER SHOW AGRIMODULE
##################
@agrimodule_bp.route('/', methods=['GET'])
@agrimodule_bp.route('/<agrimodule_id>', methods=['GET'])
@login_required
def show_agrimodule(agrimodule_id = None):

    if agrimodule_id == None:
        flash('page not allowed')
        return redirect(url_for(main.index))

    if Agrimodule.query.filter_by(id=agrimodule_id).first() == None:
        flash('That agrimodule do NOT exist')
        return redirect(url_for(main.index))

    user = current_user
    agrimodule = current_user.agrimodules.filter_by(id = agrimodule_id).first()
    # TODO: better filter the farm and field and the crop that is being passed to render in MAIN and AGRIMODULE blueprint with agrisensor in agrimodule blueprint also checked

    # TODO: here is for only 1 crop in the field. but when mix cultivation or multi. need to reflect more than 1 crop
    field = Field.query.filter_by(id = agrimodule.field_id).first()
    farm = user.farms.filter_by(id = field.farm_id).first()
    system_name = agrimodule.name
    crop = field.crops.first()
    measurement = agrimodule.measurements.order_by(Measurement.timestamp.desc()).first()

    return render_template('agrimodule/show.html', sensor_id = agrimodule_id, sensor = agrimodule, measurement = measurement, crop = crop, farm = farm, field = field, sensortype = 'Agrimodule', system_name = system_name)

##################
# USER SHOW AGRISENSOR
##################
@agrimodule_bp.route('/<agrimodule_id>/agrisensor', methods=['GET'])
@agrimodule_bp.route('/<agrimodule_id>/agrisensor/<agrisensor_id>', methods=['GET'])
@login_required
def show_agrisensor(agrimodule_id = None, agrisensor_id = None):

    if Agrimodule.query.filter_by(id=agrimodule_id).first() == None:
        flash('That agrimodule do NOT exist')
        return redirect(url_for(main.index))
    if Agrisensor.query.filter_by(id=agrisensor_id).first() == None:
        flash('That agrisensor do NOT exist')
        return redirect(url_for(main.index))

    if agrimodule_id == None:
        flash('page not allowed')
        return redirect(url_for(main.index))
    if agrisensor_id == None:
        flash('pag not allowed')
        return redirect(url_for(main.index))

    user = current_user
    agrimodule = current_user.agrimodules.filter_by(id = agrimodule_id).first()
    agrisensor = agrimodule.agrisensors.filter_by(id = agrisensor_id).first()
    field = Field.query.filter_by(id = agrimodule.field_id).first()
    farm = user.farms.filter_by(id = field.farm_id).first()
    system_name = agrimodule.name
    crop = field.crops.first()
    measurement = agrimodule.measurements.order_by(Measurement.timestamp.desc()).first()

    return render_template('agrimodule/show.html', sensor_id = agrisensor_id, sensor = agrisensor, measurement = measurement, crop = crop, farm = farm, field = field, sensortype = 'Agrisensor', system_name = system_name)


# print (crop._soil_ph_min)
# print (crop._soil_ph_max)
# print (crop._soil_temp_min)
# print (crop._soil_temp_max)
# print (crop._soil_humi_min)
# print (crop._soil_humi_max)
# print (crop._soil_nutrient_min)
# print (crop._soil_nutrient_max)
# print (crop._air_temp_min)
# print (crop._air_temp_max)
# print (crop._air_humi_min)
# print (crop._air_humi_max)

# print(ag_measurement.timestamp)
# print(ag_measurement.soil_ph)
# print(ag_measurement.soil_nutrient)
# print(ag_measurement.soil_temp)
# print(ag_measurement.soil_humi)
# print(ag_measurement.air_temp)
# print(ag_measurement.air_humi)
# print(ag_measurement.air_pres)
# print(ag_measurement.solar_radiation)
# print(ag_measurement.batt_status)
# print(ag_measurement.lat)
# print(ag_measurement.lon)

AgrimoduleSoftware/ASS/ass/solarvibes/agripump/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from solarvibes.models import User, Agripump, Agrimodule, Field
from flask_login import current_user
from flask_security import login_required

agripump_bp = Blueprint(
    'agripump_bp',
    __name__,
    template_folder="templates"
)


##################
# USER AGRIPUMP
##################
@agripump_bp.route('/', methods=['GET'])
@agripump_bp.route('/<agripump_id>', methods=['GET'])
@login_required
def show(agripump_id = None):

    # Validation
    if agripump_id == None:
        flash('page not allowed')
        return redirect(url_for('main.index'))

    if Agripump.query.filter_by(id=agripump_id).first() == None:
        flash('That agripump do NOT exist')
        return redirect(url_for('main.index'))

    # objects query
    user = current_user
    agripump = Agripump.query.filter_by(id = agripump_id).first()
    agrimodule = Agrimodule.query.filter_by(id = agripump.agrimodule_id).first()
    field = Field.query.filter_by(id = agrimodule.field_id).first()
    farm = user.farms.filter_by(id = field.farm_id).first()
    crop = field.crops.first()


    pump = user.pumps.filter_by(id = agripump.pump_id).first()
    print(user)
    print(farm)
    print(crop)
    print(pump)
    print(agripump)

    # calculating pump information
    def mlpm_to_lps(mlpm):
        return mlpm / (1000 * 60)
    def cm_to_m(cm):
        return cm / 100
    def w_to_kw(w):
        return w / 1000
    pump_info = {'pump_name': pump.pump_name, 'pump_brand': pump.pump_brand, 'pump_flow_rate':mlpm_to_lps(pump.pump_flow_rate), 'pump_watts':w_to_kw(pump.pump_watts), 'pump_head':cm_to_m(pump.pump_head)}

    # Calculating energy consumption full cycle
    def w_to_wm(w):
        return w * 60
    def wm_to_kwh(wm):
        return wm / (60 * 60 * 1000)

    pump_Wmin_consumption = w_to_wm(pump.pump_watts)
    pump_minutes_on = field.field_water_required_day / pump.pump_flow_rate
    pump_Wmin_conmsumption_on = pump_Wmin_consumption * pump_minutes_on
    pump_consumption_kwh_per_day = wm_to_kwh(pump_Wmin_conmsumption_on)
    # pump_consumption = {'' : , '' : , '' : , '' : , '' : , '' : , }

    return render_template('agripump/show.html',
                            pump = pump_info,
                            agripump = agripump,
                            farm = farm,
                            field = field,
                            crop = crop,
                            pump_consumption_kwh_per_day=pump_consumption_kwh_per_day,
                            sensortype = 'Agripump',
                            system_name = agrimodule.name)





# AGRIPUMP
# TIME USAGE
# start_hour_per_day = db.Column(db.Integer)
# qty_hour_per_day = db.Column(db.Integer)

# time_per_hour = db.Column(db.Float)
# time_per_day = db.Column(db.Float)
# time_per_cycle = db.Column(db.Float)
# WATER USAGE
# water_per_hour = db.Column(db.Integer)
# water_per_day = db.Column(db.Integer)
# water_per_cycle = db.Column(db.Integer)
# ENERGY USAGE
# energy_per_hour = db.Column(db.Integer)
# energy_per_day = db.Column(db.Integer)
# energy_per_cycle = db.Column(db.Integer)

# PUMP
# brand = db.Column(db.String(25))
# flow_rate = db.Column(db.Float(precision=2), nullable=False)
# height_max = db.Column(db.Float(presicion=2), nullable=False)
# wh = db.Column(db.Float(precision=2), nullable=False)

AgrimoduleSoftware/ASS/ass/solarvibes/main/views.py
from flask import Blueprint, render_template
from solarvibes.models import Field, Pump
from flask_login import current_user
from flask_security import login_required
from datetime import datetime, timezone


main = Blueprint(
    'main',
    __name__,
    template_folder="templates"
)


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    default_farm = current_user.farms.filter_by(_default = True).one()
    fields = Field.query.filter_by(farm_id = default_farm.id).all()
    pump_db = Pump.query
    return render_template('main/index.html',
                                user=current_user,
                                default_farm = default_farm,
                                fields = fields,
                                pump_db =pump_db,
                                timenow=datetime.now(timezone.utc))

AgrimoduleSoftware/ASS/ass/solarvibes/templates/_renderfield.html
{% macro render_field_with_errors(field) %}

	<div class="input-field">
		{{ field(**kwargs)|safe }} {{ field.label }}
	</div>
	{% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li style="color: red;">{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
{% endmacro %}

{% macro render_field(field) %}
	{{ field.label }}
	{{ field(**kwargs)|safe }}
{% endmacro %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/base_auth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>Login Page | Materialize - Material Design Admin Template</title>
    <!-- Favicons-->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="../../images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->
    <!-- CORE CSS-->
    <link href="{{ url_for('static', filename='css/themes/collapsible-menu/materialize.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/themes/collapsible-menu/style.css') }}" type="text/css" rel="stylesheet">
    <!-- Custome CSS-->
    <link href="{{ url_for('static', filename='css/custom/custom.css') }}" type="text/css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/layouts/page-center.css') }}" type="text/css" rel="stylesheet">
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="{{ url_for('static', filename='vendors/perfect-scrollbar/perfect-scrollbar.css') }}" type="text/css" rel="stylesheet">
  </head>

  <body class="svyellow">
    <!-- Start Page Loading -->
    <div id="loader-wrapper">
      <div id="loader"></div>
      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>
    </div>
    <!-- End Page Loading -->

    {% block content %} {% endblock %}
    <!-- ================================================
    Scripts
    ================================================ -->
    <!-- jQuery Library -->
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/jquery-3.2.1.min.js') }}"></script>
    <!--materialize js-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <!--custom-script.js - Add your own theme custom JS-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/custom-script.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.datepicker_sv').datepicker({
                selectMonths: true,
                selectYears: 50,
                CLoseOnSelect: true
            });
          });
    </script>

  </body>
</html>

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_alerts.html
{% extends 'base.html' %}

{% block title %}
	Alerts
{% endblock %}


{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Alerts</h1>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop planning</a><br></li>
          <li><a href="{{ url_for('user_resources') }}" style="color:#16B6A5;">Resources</a><br></li>
          <li><a href="{{ url_for('user_crop_analyzer') }}" style="color:#16B6A5;">Crop analyzer</a><br></li>
          <li><a href="{{ url_for('user_health_analyzer') }}" style="color:#16B6A5;">Health analyzer</a><br></li>
          <li><a href="{{ url_for('user_weather') }}" style="color:#16B6A5;">Weather</a><br></li>
          <li><a href="{{ url_for('user_market') }}" style="color:#16B6A5;">Market</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_crop_analyzer.html
{% extends 'base.html' %}

{% block title %}
	Crop Analyzer
{% endblock %}

{% block user_crop_analyzer_active %}
fh5co-active
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Crop analyzer</h1>
  <div>
        <hr>
        <p>Farmer links</p>
        <ul>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop planning</a><br></li>
          <li><a href="{{ url_for('user_resources') }}" style="color:#16B6A5;">Resources</a><br></li>
          <li><a href="{{ url_for('user_crop_analyzer') }}" style="color:#16B6A5;">Crop analyzer</a><br></li>
          <li><a href="{{ url_for('user_health_analyzer') }}" style="color:#16B6A5;">Health analyzer</a><br></li>
        </ul>
  </div>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_health_analyzer.html
{% extends 'base.html' %}

{% block title %}
	Health analyzer
{% endblock %}

{% block user_health_analyzer_active %}
fh5co-active
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Health analyzer</h1>
  <div>
        <hr>
        <p>Farmer links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop planning</a><br></li>
          <li><a href="{{ url_for('user_resources') }}" style="color:#16B6A5;">Resources</a><br></li>
          <li><a href="{{ url_for('user_crop_analyzer') }}" style="color:#16B6A5;">Crop analyzer</a><br></li>
          <li><a href="{{ url_for('user_health_analyzer') }}" style="color:#16B6A5;">Health analyzer</a><br></li>
        </ul>
  </div>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_market.html
{% extends 'base.html' %}

{% block title %}
	Market
{% endblock %}

{% block user_market_active %}
fh5co-active
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
   		<h1>Market</h1>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_resources.html
{% extends 'base.html' %}

{% block title %}
	Resources
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Resources</h1>
  <div>
        <hr>
        <p>Farmer links</p>
        <ul>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop planning</a><br></li>
          <li><a href="{{ url_for('user_resources') }}" style="color:#16B6A5;">Resources</a><br></li>
          <li><a href="{{ url_for('user_crop_analyzer') }}" style="color:#16B6A5;">Crop analyzer</a><br></li>
          <li><a href="{{ url_for('user_health_analyzer') }}" style="color:#16B6A5;">Health analyzer</a><br></li>
        </ul>
  </div>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop Planning</a><br></li>
          <li><a href="{{ url_for('agripump_bp.show') }}" style="color:#16B6A5;">Agripump</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/templates/user_weather.html
{% extends 'base.html' %}

{% block title %}
	Weather
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Weather</h1>
	<div>
        <hr>
        <p>General links</p>
        <ul>
          <li><a href="{{ url_for('main.index') }}" style="color:#16B6A5;">Home</a><br></li>
          <li><a href="{{ url_for('user_crop_planning') }}" style="color:#16B6A5;">Crop Planning</a><br></li>
          <li><a href="{{ url_for('agripump_bp.show') }}" style="color:#16B6A5;">Agripump</a><br></li>
          <li><a href="{{ url_for('agrimodule_bp.show') }}" style="color:#16B6A5;">Agrimodule</a><br></li>
        </ul>
	</div>

</div>

{% endblock %}