AgrimoduleSoftware/ASS/ass/solarvibes/crop_status/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from solarvibes.models import User, Field, Farm, Agrimodule
from flask_login import current_user
from flask_security import login_required
from datetime import datetime, timezone

crop_status = Blueprint(
    'crop_status',
    __name__,
    template_folder="templates"
)


##################
# USER CROP STATUS
##################
@crop_status.route('/', methods=['GET'])
@crop_status.route('/<field_id>', methods=['GET'])
@login_required
def show(field_id = None):

    # validation
    if field_id == None:
        flash('page not allowed')
        return redirect(url_for('main.index'))

    if Field.query.filter_by(id=field_id).first() == None:
        flash('That agrimodule do NOT exist')
        return redirect(url_for('main.index'))

    def cm2_to_m2(cm2):
            return cm2 / 10000

    def m2_to_cm2(m2):
            return m2 * 10000

    # db objects
    user = current_user
    field = Field.query.filter_by(id = field_id).first()
    agrimodule = Agrimodule.query.filter_by(field_id = field.id).first()
    farm = Farm.query.filter_by(id = field.farm_id).first()
    # TODO: here is for only 1 crop in the field. but when mix cultivation or multi. need to reflect more than 1 crop
    crop = field.crops.first()

    cycle_days_so_far = ( datetime.now(timezone.utc) - field.field_cultivation_start_date ).days
    today = datetime.now(timezone.utc)

    time_bar_percentage = (cycle_days_so_far * 100) / (crop._dtm + crop._dtg)
    yield_bar_percentage = (field.field_current_yield * 100) / (field.field_projected_yield)

    return render_template('crop_status/show.html',
                                crop = crop,
                                farm = farm,
                                field = field,
                                today = today,
                                cycle_days_so_far = cycle_days_so_far,
                                time_bar_percentage = time_bar_percentage,
                                yield_bar_percentage = yield_bar_percentage,
                                system_name = agrimodule.name)


##################
# USER CROP STATUS
##################
@crop_status.route('/show-all', methods=['GET'])
@login_required
def show_all():

    def cm2_to_m2(cm2):
            return cm2 / 10000

    def m2_to_cm2(m2):
            return m2 * 10000

    # db objects
    default_farm = current_user.farms.filter_by(_default = True).one()
    fields = default_farm.fields.all()

    # TODO: here is for only 1 crop in the field. but when mix cultivation or multi. need to reflect more than 1 crop
    # crop = field.crops.first()

    today = datetime.now(timezone.utc)
    # cycle_days_so_far = ( today - field.field_cultivation_start_date ).days


    # time_bar_percentage = (cycle_days_so_far * 100) / (crop._dtm + crop._dtg)
    # yield_bar_percentage = (field.field_current_yield * 100) / (field.field_projected_yield)

    return render_template('crop_status/show_all.html',
                                fields = fields,
                                today = today)

AgrimoduleSoftware/ASS/ass/solarvibes/crop_status/templates/crop_status/show.html
{% extends 'base.html' %}

{% block title %}
	Agrimodule
{% endblock %}

{% block links_in_head %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
{% endblock links_in_head %}

{% block css_in_head %}
<style type="text/css">
	.outter-color{background-color: rgba(255, 255, 0, 0.3) !important;}
	.inner-color{background-color: rgba(255, 255, 0, 0.5) !important;}
	.bg_y{background-color: yellow;}
	.bg_b{background-color: blue;}
	.bg_gr{background-color: gray;}
	.bg_r{background-color: red;}
	.bg_g{background-color: green;}
	.bg_dgr{background-color: darkgray;}
	.bg_lgr{background-color: lightgray;}
	.centrado{text-align: center;}
	.padding{padding: 10px !important;}
	.margin{margin: 10px !important;}
	.margin-tp{margin: 10px 0 10px 0 !important;}
</style>
{% endblock css_in_head %}

{% block links_body %}
{% endblock links_body %}


{% block content %}

	<nav class="container svgreen lighten-2 margin-top">
		<div class="nav-wrapper">
			<div class="col s12">
				<a class="breadcrumb">{{ farm.farm_name }}</a>
				<a class="breadcrumb">{{ field.field_name }}</a>
				<a class="breadcrumb">{{ system_name }}</a>
			</div>
		</div>
	</nav>
	<!-- outter box -->
	<div class="padding box margin z-depth-2">

		<!-- header -->
		<div class="row margin">
			<div class="col s12 m12">
				<div class="row">
					<div class="col s8 offset-s2 center">

					</div>
					<div class="col s1 offset-s1 right right-align">
						<a href="{{ url_for('main.index') }}">
							<i class="far fa-2x fa-window-close yellow"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- end header -->

		<!-- inner box -->
		<div class="row box margin-tp padding-tp">
			<div class="col s12 m12 offset-">

				<!-- main UI title -->
				<div class="row center padding">
					<div class="col s6">
						<h5>CROP INFORMATION</h5>
					</div>
					<div class="col s3">
						<h5>RESOURCES STATUS</h5>
					</div>
					<div class="col s3">
						<h5>TIME & YIELD</h5>
					</div>
				</div>
				<!-- end main UI title -->

				<!-- main UI content -->
				<div class="row center valign-wrapper margin-tp">
					<!-- crop Information content -->
					<div class="col s6 margin-tp">
						<!-- crop data -->
						<div class="row valign-wrapper">
							<div class="col s6 box z-depth-3">
								<div class="col s12 padding"><h5>{{ crop._variety|capitalize }}</h5></div>
								<br><br>
								<div class="col s12 blue lighten-2 padding margin-tp"><img class="responsive-img" src="{{ crop.image }}"></div>
							</div>
							<div class="col s4 offset-s1 left-align">
								<div class="col s12 teal-text text-lighten-2 padding"><h6>Crop Data:</h6></div>
								<div class="col s12">{{ crop._name|capitalize }}</div>
								<div class="col s12">{{ field.field_cultivation_area / 10000 }} m<sup>2</sup></div>
								<div class="col s12">{{ field.field_num_plants }} plants</div>
								<!-- TODO: density must be calculated dynamically with space it takes and not from db field -->
								<div class="col s12">{{ crop._density * 10000 }} plants / m<sup>2</sup></div>
							</div>
						</div>
						<!-- end crop data -->

						<!-- time -->
						<div class="row center margin-tp">
							<div class="col s12">
								<div class="col s4">
									<p>Begin</p>
								</div>
								<div class="col s4">
									<p class="svgreen-text">Today</p>
								</div>
								<div class="col s4">
									<p>End</p>
								</div>

								<div class="col s12">
									<progress class="progress is-danger z-depth-3 progress-height" value="{{ time_bar_percentage }}" max="100">{{ time_bar_percentage }}%</progress>
								</div>

								<div class="col s4">
									<p>{{ field.field_cultivation_start_date.strftime('%A, %b %d, %Y') }}</p>
								</div>
								<div class="col s4 svgreen-text">
									<h6>{{ today.strftime('%A, %b %d, %Y') }}</h6>
								</div>
								<div class="col s4">
									<p>{{ field.field_cultivation_finish_date.strftime('%A, %b %d, %Y') }}</p>
								</div>

							</div>

						</div>
						<!-- end time -->
					</div>
					<!-- end crop Information content -->


					<div class="vl z-depth-3"></div>


					<!-- crop alerts -->
					<div class="col s3">
						<div class="row center-align margin-tp">
							<div class="col s12 margin-tp"><h5>Water</h5></div>
							<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-tint blue-text text-lighten-2"></i></div>
						</div>

						<div class="row center-align margin-tp">
							<div class="col s12 margin-tp"><h5>Radiation</h5></div>
							<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-sun yellow-text text-lighten-2"></i></div>
						</div>

						<div class="row center-align margin-tp">
							<div class="col s12 margin-tp"><h5>Fertilizer<span class="new badge red">4</span></h5></div>
							<div class="col s6"><i class="far fa-2x fa-times-circle red-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-leaf teal-text text-lighten-2"></i></div>
						</div>
					</div>
					<!-- end crop alerts -->

					<div class="vl z-depth-3"></div>

					<!-- time and yield -->
					<div class="col s3">
						<div class="col s12 margin-tp">
							<div class="col s12 padding"><h5>Cycle time</h5></div>
							<div class="col s6 left-align">current</div>
							<div class="col s6 right-align">total</div>
							<div class="col s12">
								<progress class="progress is-success z-depth-3 progress-height" value="{{ time_bar_percentage }}" max="100">{{ time_bar_percentage }}%</progress>
							</div>
							<div class="col s5 left-align">
								{% if cycle_days_so_far >= 0: %}
							    	{{ cycle_days_so_far }}
							 	{% else %}
							   		{{ 'Starts in ' + cycle_days_so_far|abs|string }}
							 	{% endif %} days
							</div>
							<div class="col s7 right-align">{{ crop._dtm + crop._dtg }} days</div>
						</div>
						<div class="col s12 margin-tp">
							<div class="col s12 padding"><h5>Yield</h5></div>
							<div class="col s6 left-align">current</div>
							<div class="col s6 right-align">total</div>
							<div class="col s12">
								<progress class="progress is-success z-depth-3 progress-height" value="{{ yield_bar_percentage }}" max="100">{{ yield_bar_percentage }}%</progress>
							</div>
							<div class="col s5 left-align">{{ field.field_current_yield / 1000 }} kg</div>
							<div class="col s7 right-align">{{ field.field_projected_yield / 1000 }} kg</div>
						</div>

					</div>
					<!-- end time and yield -->

				</div>
				<!-- end main UI content -->

			</div>
		</div>
		<!-- end inner box -->
	</div>
	<!-- end outter box -->
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/crop_status/templates/crop_status/show1.html
{% extends 'base.html' %}

{% block title %}
	Crop status
{% endblock %}

{% block crop_status_active %}
active
{% endblock %}

{% block content %}
<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
	<div style="padding-left: 2%; text-align: left;">
    <h1>Crop status</h1>
  <div>
        <hr>
        <p>Crop information</p>
        <ul>
          <li>Variety:             <span style="color: black;">       {{ crop._variety|capitalize }}                                  </span>  </li>
          <li>Name:                <span style="color: black;">       {{ crop._name|capitalize }}                                     </span>  </li>
          <li>Area cultivated:     <span style="color: black;">       {{ field.field_cultivation_area / 10000 }} m<sup>2</sup>        </span>  </li>
          <li>Amount of plants:    <span style="color: black;">       {{ field.field_num_plants }}                                    </span>  </li>
          <li>Start cultivation:   <span style="color: black;">       {{ field.field_cultivation_start_date.strftime('%A, %b %d, %Y') }}  </span>  </li>
          <li>Finish cultivation:  <span style="color: black;">       {{ field.field_cultivation_finish_date.strftime('%A, %b %d, %Y') }} </span>  </li>
        </ul>
  </div>

  <div>
        <hr>
        <p>Resources status</p>
        <ul>
          <li><i>         Water:                Ok                         </i></li>
          <li><i>         Fertilizer:           ~Ok                        </i></li>
          <li><i>         Radiation:            Ok                         </i></li>
          <li><i>         Status icon:          Icon                       </i></li>
        </ul>
  </div>

  <div>
        <hr>
        <p>Time / Yield</p>
        <ul>
          <li>Time</li>
          <li>            Cycle:        <span style="color: black;">      {{ crop._dtm + crop._dtg }} days                            </span>  </li>
          <li>            So far:       <span style="color: black;">
                                                                          {% if cycle_days_so_far >= 0 %}
                                                                            {{ cycle_days_so_far }}
                                                                          {% else %}
                                                                            {{ 'Your cultivation starts in ' + cycle_days_so_far|abs|string }}
                                                                          {% endif %}
                                                                                                                days                  </span>  </li>

          <li>Yield</li>
          <li>            Projected:    <span style="color: black;">       {{ field.field_projected_yield / 1000 }} kg                </span>  </li>
          <li>            So far:       <span style="color: black;">       {{ field.field_current_yield / 1000 }} kg                  </span>  </li>
        </ul>
  </div>

</div>

{% endblock %}

<!-- <div>
	<hr>
	<p>General links</p>
	<ul>
	  <li><a href="#" style="color:#16B6A5;">Home</a><br></li>
	  <li><a href="#" style="color:#16B6A5;">Agrimodule</a><br></li>
	  <li><a href="#" style="color:#16B6A5;">Agripump</a><br></li>
	  <li><a href="#" style="color:#16B6A5;">Alerts</a><br></li>
	</ul>
</div> -->

AgrimoduleSoftware/ASS/ass/solarvibes/crop_status/templates/crop_status/show_all.html
{% extends 'base.html' %}

{% block title %}
	Agrimodule
{% endblock %}

{% block links_in_head %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
{% endblock links_in_head %}

{% block css_in_head %}
{% endblock css_in_head %}

{% block links_body %}
{% endblock links_body %}


{% block content %}
	<!-- outter box -->
	<div class="margin-tp box z-depth-2">

		<!-- header -->
		<div class="row margin">
			<div class="col s12 m12">
				<div class="row">
					<div class="col s8 offset-s2 center">

					</div>
					<div class="col s1 offset-s1 right right-align">
						<a href="{{ url_for('main.index') }}">
							<i class="far fa-2x fa-window-close yellow"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- end header -->



		<div class="row">
			{% for field in fields: %}
			<a href="{{ url_for('crop_status.show', field_id = field.id) }}">
				<div class="col s12 m12 l12 xl6">
					<!-- inner box -->
					<div class="row box inner-color margin-tp hoverable">
						<div class="col s12">

							<!-- main UI title -->
							<div class="row center ">
								<div class="col s6">
									<h5>CROP INFORMATION</h5>
								</div>
								<div class="col s3">
									<h5>RESOURCES STATUS</h5>
								</div>
								<div class="col s3">
									<h5>TIME & YIELD</h5>
								</div>
							</div>
							<!-- end main UI title -->

							<!-- main UI content -->
							<div class="row center valign-wrapper margin-tp">
								<!-- crop Information content -->
								<div class="col s6 margin-tp">
									<!-- crop data -->
									<div class="row valign-wrapper">
										<div class="col s6 box z-depth-3">
											<div class="col s12 "><h5>{{ field.crops.first()._variety|capitalize }}</h5></div>
											<br><br>
											<div class="col s12 blue lighten-2  margin-tp"><img class="responsive-img" src="{{ field.crops.first().image }}"></div>
										</div>
										<div class="col s4 offset-s1 left-align">
											<div class="col s12 teal-text text-lighten-2 "><h6>Crop Data:</h6></div>
											<div class="col s12">{{ field.crops.first()._name|capitalize }}</div>
											<div class="col s12">{{ field.field_cultivation_area / 10000 }} m<sup>2</sup></div>
											<div class="col s12">{{ field.field_num_plants }} plants</div>
											<!-- TODO: density must be calculated dynamically with space it takes and not from db field -->
											<div class="col s12">{{ field.crops.first()._density * 10000 }} plants / m<sup>2</sup></div>
										</div>
									</div>
									<!-- end crop data -->

									<!-- time -->
									<div class="row center margin-tp">
										<div class="col s12">
											<div class="col s4">
												<p>Begin</p>
											</div>
											<div class="col s4">
												<p class="svgreen-text">Today</p>
											</div>
											<div class="col s4">
												<p>End</p>
											</div>

											<div class="col s12">
												<progress class="progress is-danger z-depth-3 progress-height" value="{{ (( today - field.field_cultivation_start_date ).days * 100) / (field.crops.first()._dtm + field.crops.first()._dtg) }}" max="100">{{ (( today - field.field_cultivation_start_date ).days * 100) / (field.crops.first()._dtm + field.crops.first()._dtg) }}%</progress>
											</div>

											<div class="col s4">
												<p>{{ field.field_cultivation_start_date.strftime('%A, %b %d, %Y') }}</p>
											</div>
											<div class="col s4 svgreen-text">
												<h6>{{ today.strftime('%A, %b %d, %Y') }}</h6>
											</div>
											<div class="col s4">
												<p>{{ field.field_cultivation_finish_date.strftime('%A, %b %d, %Y') }}</p>
											</div>

										</div>

									</div>
									<!-- end time -->
								</div>
								<!-- end crop Information content -->


								<div class="vl z-depth-3"></div>


								<!-- crop alerts -->
								<div class="col s3">
									<div class="row center-align margin-tp">
										<div class="col s12 margin-tp"><h5>Water</h5></div>
										<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
										<div class="col s6"><i class="fas fa-2x fa-tint blue-text text-lighten-2"></i></div>
									</div>

									<div class="row center-align margin-tp">
										<div class="col s12 margin-tp"><h5>Radiation</h5></div>
										<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
										<div class="col s6"><i class="fas fa-2x fa-sun yellow-text text-lighten-2"></i></div>
									</div>

									<div class="row center-align margin-tp">
										<div class="col s12 margin-tp"><h5>Fertilizer<span class="new badge red">4</span></h5></div>
										<div class="col s6"><i class="far fa-2x fa-times-circle red-text"></i></div>
										<div class="col s6"><i class="fas fa-2x fa-leaf teal-text text-lighten-2"></i></div>
									</div>
								</div>
								<!-- end crop alerts -->

								<div class="vl z-depth-3"></div>

								<!-- time and yield -->
								<div class="col s3">
									<div class="col s12 margin-tp">
										<div class="col s12 "><h5>Cycle time</h5></div>
										<div class="col s6 left-align">current</div>
										<div class="col s6 right-align">total</div>
										<div class="col s12">
											<progress class="progress is-success z-depth-3 progress-height" value="{{ (( today - field.field_cultivation_start_date ).days * 100) / (field.crops.first()._dtm + field.crops.first()._dtg) }}" max="100">{{ (( today - field.field_cultivation_start_date ).days * 100) / (field.crops.first()._dtm + field.crops.first()._dtg) }}%</progress>
										</div>
										<div class="col s5 left-align">
											{% if ( today - field.field_cultivation_start_date ).days >= 0: %}
										    	{{ ( today - field.field_cultivation_start_date ).days }}
										 	{% else %}
										   		{{ 'Starts in ' + ( today - field.field_cultivation_start_date ).days|abs|string }}
										 	{% endif %} days
										</div>
										<div class="col s7 right-align">{{ field.crops.first()._dtm + field.crops.first()._dtg }} days</div>
									</div>
									<div class="col s12 margin-tp">
										<div class="col s12 "><h5>Yield</h5></div>
										<div class="col s6 left-align">current</div>
										<div class="col s6 right-align">total</div>
										<div class="col s12">
											<progress class="progress is-success z-depth-3 progress-height" value="{{ (field.field_current_yield * 100) / (field.field_projected_yield) }}" max="100">{{ (field.field_current_yield * 100) / (field.field_projected_yield) }}%</progress>
										</div>
										<div class="col s5 left-align">{{ field.field_current_yield / 1000 }} kg</div>
										<div class="col s7 right-align">{{ field.field_projected_yield / 1000 }} kg</div>
									</div>

								</div>
								<!-- end time and yield -->

							</div>
							<!-- end main UI content -->

						</div>
					</div>
					<!-- end inner box -->
				</div>
			</a>
			{% endfor %}
		</div>




	</div>
	<!-- end outter box -->
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/crop_status/templates/crop_status/show_html.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Solarvibes | {% block title %}{% endblock %}</title>

	<!-- Bulma -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">


	<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<!-- # NOT BULMA -->
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

	<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
	<style type="text/css">
		.outter-color{background-color: rgba(255, 255, 0, 0.3) !important;}
		.inner-color{background-color: rgba(255, 255, 0, 0.5) !important;}
		.bg_y{background-color: yellow;}
		.bg_b{background-color: blue;}
		.bg_gr{background-color: gray;}
		.bg_r{background-color: red;}
		.bg_g{background-color: green;}
		.bg_dgr{background-color: darkgray;}
		.bg_lgr{background-color: lightgray;}
		.centrado{text-align: center;}
		.padding{padding: 10px;}
		.margin{margin: 10px;}

		.flip_90 {
		    -webkit-transform: rotate(90deg);
		    -moz-transform: rotate(90deg);
		    -o-transform: rotate(90deg);
		    -ms-transform: rotate(90deg);
		    transform: rotate(90deg);
		}
		.flip_180 {
		    -webkit-transform: rotate(180deg);
		    -moz-transform: rotate(180deg);
		    -o-transform: rotate(180deg);
		    -ms-transform: rotate(180deg);
		    transform: rotate(180deg);
		}
		.flip_270 {
		    -webkit-transform: rotate(270deg);
		    -moz-transform: rotate(270deg);
		    -o-transform: rotate(270deg);
		    -ms-transform: rotate(270deg);
		    transform: rotate(270deg);
		}
		.progress-height{
			height: 10px !important;
		}
	</style>
	<script type="text/javascript">
        document.getElementById("nav-toggle").addEventListener ("click", toggleNav);
        function toggleNav() {
                var nav = document.getElementById("nav-menu");
                var className = nav.getAttribute("class");
                if(className == "nav-right nav-menu") {
                    nav.className = "nav-right nav-menu is-active";
                } else {
                    nav.className = "nav-right nav-menu";
                }
        }
    </script>
</head>
<body>

	<!-- outter box -->
	<div class="container outter-color padding">

		<!-- header -->
		<div class="row">
			<div class="col s12 m10 offset-m1">
				<div class="row">
					<div class="col s8 offset-s2 center">Tabs</div>
					<div class="col s1 offset-s1 right right-align">
						<i class="far fa-2x fa-window-close"></i>
					</div>
				</div>
			</div>
		</div>
		<!-- end header -->

		<!-- inner box -->
		<div class="row inner-color">
			<div class="col s12 m10 offset-m1">

				<!-- main UI title -->
				<div class="row center">
					<div class="col s6">
						<h5>CROP INFORMATION</h5>
					</div>
					<div class="col s3">
						<h5>RESOURCES STATUS</h5>
					</div>
					<div class="col s3">
						<h5>TIME & YIELD</h5>
					</div>
				</div>
				<!-- end main UI title -->

				<!-- main UI content -->
				<div class="row center valign-wrapper">
					<!-- crop Information content -->
					<div class="col s6">
						<!-- crop data -->
						<div class="row valign-wrapper padding">
							<div class="col s6 box z-depth-3">
								<div class="col s12"><h6>Tomato</h6></div>
								<br><br>
								<div class="col s12 blue lighten-2 margin"><img class="responsive-img" src="../../../static/bulma/tomato.png"></div>
							</div>
							<div class="col s6 left-align">
								<div class="col s12 teal-text text-lighten-2"><h6>Crop Data:</h6></div>
								<div class="col s12">Plum</div>
								<div class="col s12">780 m<sup>2</sup></div>
								<div class="col s12">3120 plants</div>
								<div class="col s12">4 plants / m<sup>2</sup></div>
							</div>
						</div>
						<!-- end crop data -->

						<!-- time -->
						<div class="row center">
							<div class="col s12">
								<div class="col s4">
									<p>Begin</p>
								</div>
								<div class="col s4">
									<p>Today</p>
								</div>
								<div class="col s4">
									<p>End</p>
								</div>

								<div class="col s12">
									<progress class="progress is-danger z-depth-3 progress-height" value="70" max="100">15%</progress>
								</div>

								<div class="col s4">
									<p>April 1st, 2018</p>
								</div>
								<div class="col s4">
									<h6>June 5th, 2018</h6>
								</div>
								<div class="col s4">
									<p>July 3rd, 2018</p>
								</div>

							</div>

						</div>
						<!-- end time -->
					</div>
					<!-- end crop Information content -->

					<!-- crop alerts -->
					<div class="col s3">
						<div class="row center-align">
							<div class="col s12"><h5>Water</h5></div>
							<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-tint blue-text text-lighten-2"></i></div>
						</div>

						<div class="row center-align">
							<div class="col s12"><h5>Radiation</h5></div>
							<div class="col s6"><i class="far fa-2x fa-check-circle green-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-sun yellow-text text-lighten-2"></i></div>
						</div>

						<div class="row center-align">
							<div class="col s12"><h5>Fertilizer<span class="new badge red">4</span></h5></div>
							<div class="col s6"><i class="far fa-2x fa-times-circle red-text"></i></div>
							<div class="col s6"><i class="fas fa-2x fa-leaf teal-text text-lighten-2"></i></div>
						</div>
					</div>
					<!-- end crop alerts -->

					<!-- time and yield -->
					<div class="col s3">
						<div class="col s12">
							<div class="col s12"><h5>Cycle time</h5></div>
							<div class="col s4 left-align">current</div>
							<div class="col s8 right-align">total</div>
							<div class="col s12">
								<progress class="progress is-success z-depth-3 progress-height" value="3" max="100">15%</progress>
							</div>
							<div class="col s4 left-align">7</div>
							<div class="col s8 right-align">180 days</div>
						</div>
						<div class="col s12">
							<div class="col s12"><h5>Yield</h5></div>
							<div class="col s4 left-align">current</div>
							<div class="col s8 right-align">total</div>
							<div class="col s12">
								<progress class="progress is-success z-depth-3 progress-height" value="1" max="100">15%</progress>
							</div>
							<div class="col s4 left-align">0</div>
							<div class="col s8 right-align">4.48 tons</div>
						</div>

					</div>
					<!-- end time and yield -->

				</div>
				<!-- end main UI content -->

			</div>
		</div>
		<!-- end inner box -->
	</div>
	<!-- end outter box -->

</body>
</html>