AgrimoduleSoftware/ASS/ass/solarvibes/welcome/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from solarvibes import db
from solarvibes.welcome.forms import PreAddFarmForm, AddFarmForm, PreAddSoilTestForm, AddSoilTestForm, PreAddWaterTestForm, AddWaterTestForm, AddCropForm, PreAddCropForm, AddAgrisysForm, PreAddAgrisysForm, InstallAgrisysForm, PreInstallAgrisysForm, AddPumpForm, PreAddPumpForm
from solarvibes.models import User, Crop, Farm, Field, Pump, Agrimodule, Agrisensor, Agripump, SoilTest, WaterTest
from solarvibes.models import AgrimoduleList, AgrisensorList, AgripumpList
from solarvibes.models import WelcomeLog
from flask_login import current_user
from flask_security import login_required
from math import sqrt, floor
from datetime import datetime, timedelta

welcome = Blueprint(
    'welcome',
    __name__,
    template_folder="templates"
)

#############################
#############################
# WELCOME VIEWS
#############################
#############################

###################
# WELCOME
###################
@welcome.route('/', methods=['GET'])
@login_required
def index():
    if 'welcome' not in session:
        session['welcome'] = dict()
        session.modified = True

    # if user hasnot yet a welcome_log, then created
    if not current_user.welcome:
        welcome_log = WelcomeLog(   user = current_user,
                                    add_agrisys = False,
                                    install_agrisys = False,
                                    add_pump = False,
                                    add_farm = False,
                                    add_soil_test = False,
                                    add_water_test = False,
                                    add_field = False)
        db.session.add(welcome_log)
        db.session.commit()

    # if user have not set up any agrimodule -> we send him to set agrimodule first
    if not current_user.welcome.add_agrisys or not current_user.welcome.install_agrisys or not current_user.welcome.add_pump:
        flash('welcome for the first time, ' + current_user.name + '!')
        set_sys_flag = True
        return render_template('welcome/welcome.html', user=current_user, set_sys_flag=set_sys_flag)

    # if user have not set up any farm yet -> we send him to set his farm only
    if not current_user.welcome.add_farm or current_user.welcome.add_field:
        flash('Now set your farm, ' + current_user.name + '!')
        set_sys_flag = False
        return render_template('welcome/welcome.html', user=current_user, set_sys_flag=set_sys_flag)

    # if neither the case send him to main. he must have set up a system and a farm
    else:
        flash('you already have install agrimodule and add it to your farm, ' + current_user.name + '!')
        return redirect(url_for('main.index'))


###################
# SET CONNECT ASS
###################
@welcome.route('/add-agrisys', methods=['GET', 'POST'])
@login_required
def add_agrisys():

    if 'welcome' not in session:
        session['welcome'] = dict()
        session.modified = True

    form = AddAgrisysForm()
    # if user has complete farm, but didnot finish field. pass the current
    if current_user.welcome.add_agrisys:
        agrimodule = current_user.agrimodules.first()
        myAgrimodule = PreAddAgrisysForm(agrimodule_name = agrimodule.name, agrimodule_identifier = agrimodule.identifier)
        form = AddAgrisysForm(obj=myAgrimodule)               # CREATE WTForm FORM

    if form.validate_on_submit():
        # USER OBJS
        user = current_user

        # ADD AGRISYS OBJS
        agrimodule_name = form.agrimodule_name.data
        agrimodule_identifier = form.agrimodule_identifier.data

        # if agrimodule is register in solarvibes db
        def is_registered_in_solarvibes(identifier):
            agrimodule_reg = AgrimoduleList.query.filter_by(identifier = identifier).first()
            if not agrimodule_reg:
                return False
            return True

        # if a farmer has already registered this to him
        def is_registered_by_diff_user(identifier):
            agrimodule_reg = AgrimoduleList.query.filter_by(identifier = identifier).first()
            if agrimodule_reg.has_user_registered and current_user.id != agrimodule_reg.user_id:
                return True
            return False

        # if end with tripple zero ("0") belongs to the bundle
        def is_agrimodule_bundle(identifier):
            if identifier[-3:] == '000':
                return True
            return False

        def get_bundle_identifiers(identifier):
            agrimodule_identifier = identifier
            # //TODO: must recognize all numbers instead of the las four digits. unless a uuid is created with a standarz characters qty.
            agrisensor_identifier = 'agrisensor' + identifier[-5:]
            agripump_identifier = 'agripump' + identifier[-5:]
            return agrimodule_identifier, agrisensor_identifier, agripump_identifier

        if not is_registered_in_solarvibes(agrimodule_identifier):
            flash('agrimodule not registered in Solarvibes! Contact Solarvibes support')
            return redirect(url_for('welcome.add_agrisys', form = form))

        if is_registered_by_diff_user(agrimodule_identifier):
            flash('agrimodule is registered to another farmer! Contact Solarvibes support')
            return redirect(url_for('welcome.add_agrisys', form = form))

        try:
            if is_agrimodule_bundle(agrimodule_identifier):

                agrimodule_identifier, agrisensor_identifier, agripump_identifier = get_bundle_identifiers(agrimodule_identifier)

                if current_user.welcome.add_agrisys:
                    # OBJS TO DB
                    agrimodule = current_user.agrimodules.first()
                    agrimodule.name = agrimodule_name
                    agrimodule.identifier = agrimodule_identifier
                    agrisensor = agrimodule.agrisensors.first()
                    agrisensor.identifier = agrisensor_identifier
                    agripump = agrimodule.agripumps.first()
                    agripump.identifier = agripump_identifier

                    # FLASH
                    flash('Your agrimodule bundle has been re-registered with identifier: "{}"'.format(agrimodule_identifier))
                else:
                    # OBJS TO DB
                    agrimodule = Agrimodule(name = agrimodule_name, identifier = agrimodule_identifier, user = user, batt_status = 0, lat = 0, lon = 0)
                    agrisensor = Agrisensor(identifier = agrisensor_identifier, agrimodule = agrimodule, batt_status = 0, lat = 0, lon = 0)
                    agripump = Agripump(identifier = agripump_identifier, agrimodule = agrimodule, status = False, lat = 0, lon = 0)
                    # DB COMMANDS
                    db.session.add_all([agrimodule, agrisensor, agripump])
                    # FLASH
                    flash('Your agrimodule bundle has been registered with identifier: "{}"'.format(agrimodule_identifier))

                # update the registration form of agrimodule bundle
                agrimodule_reg = AgrimoduleList.query.filter_by(identifier = agrimodule_identifier).first()
                agrisensor_reg = AgrisensorList.query.filter_by(identifier = agrisensor_identifier).first()
                agripump_reg = AgripumpList.query.filter_by(identifier = agripump_identifier).first()
                agrimodule_reg.has_user_registered = True
                agrimodule_reg.user_id = user.id
                agrisensor_reg.has_user_registered = True
                agrisensor_reg.user_id = user.id
                agripump_reg.has_user_registered = True
                agripump_reg.user_id = user.id
            else:
                if current_user.welcome.add_agrisys:
                    # OBJS TO DB
                    agrimodule = current_user.agrimodules.first()
                    agrimodule.name = agrimodule_name
                    agrimodule.identifier = agrimodule_identifier
                    # FLASH
                    flash('Your agrimodule has been re-registered with identifier: "{}"'.format(agrimodule_identifier))
                else:
                    # OBJS TO DB
                    agrimodule = Agrimodule(name = agrimodule_name, identifier = agrimodule_identifier, user = user)
                    # DB COMMANDS
                    db.session.add(agrimodule)
                    # FLASH
                    flash('Your agrimodule has been registered with identifier: "{}"'.format(agrimodule_identifier))

                # update the registration form of agrimodule bundle
                agrimodule_reg = AgrimoduleList.query.filter_by(identifier = agrimodule_identifier).first()
                agrimodule_reg.has_user_registered = True
                agrimodule_reg.user_id = user.id

            # set welcome flag to True
            user.welcome.add_agrisys = True
            # DB COMMANDS
            db.session.commit()
            # ADD SESSION OBJS
            session['welcome'].update({'agrimodule_identifier':agrimodule_identifier, 'agrimodule_id':agrimodule.id})
            session.modified = True

            # REDIRECT
            return redirect(url_for('welcome.install_agrisys'))
        except Exception as e:
            db.session.rollback()
            flash('Error: ' + str(e))
            flash('an error has occour. Try again later!'.format(agrimodule_identifier))
            return redirect(url_for('welcome.add_agrisys', form = form))
    return render_template('welcome/add_agrisys.html', form=form)



###################
# SET INSTALL ASS
###################
@welcome.route('/install-agrisys', methods=['GET', 'POST'])
@login_required
def install_agrisys():

    # def is_agrimodule_bundle(identifier):
    #     if identifier[-3:] == '000':
    #         return True
    #     return False
    #
    # def get_bundle_identifiers(identifier):

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_agrisys.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Farm Add Agrisys
{% endblock %}

{% block add_agrisys_active %}
	active
{% endblock %}

{% block content %}
<div class = "container">
    <h4>Add_agrisys</h4>
    <form method="POST" action="{{ url_for('welcome.add_agrisys') }}">
        {{ form.csrf_token }}
		{{ render_field_with_errors(form.agrimodule_name) }}
		{{ render_field_with_errors(form.agrimodule_identifier) }}
		<input type="submit" class="hoverable waves-effect waves-light btn" value="Add agrimodule!">
	</form>
	<br>
	<a href="{{ url_for('welcome.index') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_crop.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Set field
{% endblock %}

{% block add_crop_active %}
	active
{% endblock %}

{# //TODO: datepicker needs to be formated to insert data into db #}

{% block content %}
<div class = "container">
	<h3>Welcome set field</h3>
    <hr>
	<h4>Create a field inside your farm</h4>
	<form method="POST" action="{{ url_for('welcome.add_crop') }}">
		{{ form.csrf_token }}
		{{ render_field_with_errors(form.field_cultivation_area) }}
		{{ render_field_with_errors(form.field_cultivation_crop) }}
		{{ render_field_with_errors(form.field_cultivation_start_date, class='datepicker') }}
		{{ render_field_with_errors(form.field_cultivation_state) }}
		{{ render_field_with_errors(form.field_cultivation_type) }}
		<input type="submit" class="btn btn-primary btn-md" value="Create Field!">
	</form>
	<br>
	<a href="{{ url_for('welcome.add_farm') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock content %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_farm.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Set Farm
{% endblock %}

{% block add_farm_active %}
	active
{% endblock %}

{% block map %}
  <link rel="css/sheet" type="text/css" href="css/custom/map.css">
{% endblock %}

{% block content %}

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJusa1miMBhsqN5m3oJhm6X2mmdhYqLqU&libraries=places"></script>
<!-- // Enable Place API and Map Javascript API on Google Cloud Platform for this API key -->

<div class = "container">
    <h1>Welcome add farm</h1>
    <hr>
  <h1>Create your farm</h1>

  <form method="POST" action="{{ url_for('welcome.add_farm') }}">
    {{ form.csrf_token }}
    {{ render_field_with_errors(form.farm_name) }}
    {{ render_field_with_errors(form.farm_location) }}
    {{ render_field_with_errors(form.farm_area) }}
    <!-- <div id="map" style="height: 500px;"></div> -->
    <!-- <br> -->
    {# render_field_with_errors(form.farm_coordinates) #}
    {{ render_field_with_errors(form.farm_cultivation_process) }}
    <input type="submit" class="hoverable waves-effect waves-light btn" value="Add farm!">
  </form>

  <br>

  <a href="{{ url_for('welcome.add_pump') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>

    {#<script>
      // function initMap() {
      //   var map = new google.maps.Map(document.getElementById('map'), {
      //     center: {lat: -34.397, lng: 150.644},
      //     zoom: 8
      //   });
	  //
      //   var drawingManager = new google.maps.drawing.DrawingManager({
      //     drawingMode: google.maps.drawing.OverlayType.MARKER,
      //     drawingControl: true,
      //     drawingControlOptions: {
      //       position: google.maps.ControlPosition.TOP_CENTER,
      //       drawingModes: ['marker', 'circle', 'polygon', 'polyline', 'rectangle']
      //     },
      //     markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
      //     circleOptions: {
      //       fillColor: '#ffff00',
      //       fillOpacity: 1,
      //       strokeWeight: 5,
      //       clickable: false,
      //       editable: true,
      //       zIndex: 1
      //     }
      //   });
      //   drawingManager.setMap(map);
	  //
      //   google.maps.event.addListener(drawingManager, 'polygoncomplete', function (polygon) {
      //   var coordinates = (polygon.getPath().getArray());
	  //
      //   document.getElementById("farm_coordinates").value = coordinates
      //   console.log(coordinates);
      //   });
	  // }
		var input = document.getElementById('farm_location');
		var autocomplete = new google.maps.places.Autocomplete(input,{types: ['(cities)']});
		google.maps.event.addListener(autocomplete, 'place_changed', function(){
			var place = autocomplete.getPlace();
		})


    </script>#}
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBH2_9ICY6lpK-H9o_lpmWY9Q6rzJMsJE&libraries=drawing&callback=initMap"async defer></script> -->

</div>

{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_pump.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Farm Add Pump
{% endblock %}

{% block add_pump_active %}
	active
{% endblock %}

{% block content %}
<div class = "container">
    <h4>Add Pump</h4>
	<form method="POST" action="{{ url_for('welcome.add_pump') }}">
		{{ form.csrf_token }}
		{{ render_field_with_errors(form.pump_name) }}
		{{ render_field_with_errors(form.pump_brand) }}
		{{ render_field_with_errors(form.pump_flow_rate) }}
		{{ render_field_with_errors(form.pump_head) }}
		{{ render_field_with_errors(form.pump_watts) }}
		<input type="submit" class="hoverable waves-effect waves-light btn" value="Add pump!">
	</form>
	<br>
	<a href="{{ url_for('welcome.install_agrisys') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_soil_test.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
  Add Soil Test (OptionL)
{% endblock %}

{% block add_soil_test_active %}
  active
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Welcome add soil test</h1>
    <hr>
  <h1>Add Soil Test</h1>
  <form method="POST" action="{{ url_for('welcome.add_soil_test') }}">
    {{ form.csrf_token }}
    {{ render_field_with_errors(form.soil_ph) }}
    {{ render_field_with_errors(form.soil_ec) }}
    {{ render_field_with_errors(form.soil_organic_carbon) }}
    {{ render_field_with_errors(form.soil_nitrogen) }}
    {{ render_field_with_errors(form.soil_p205) }}
    {{ render_field_with_errors(form.soil_k20) }}
    <input type="submit" class="hoverable waves-effect waves-light btn" value="Add soil test!">
  </form>
  <br>
  <a href="{{ url_for('welcome.add_farm') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/add_water_test.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
  Add Water Test (Optional)
{% endblock %}

{% block add_water_test_active %}
  active
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Welcome add water test</h1>
    <hr>
  <h1>Add Water Test</h1>
  <form method="POST" action="{{ url_for('welcome.add_water_test') }}">
    {{ form.csrf_token }}
    {{ render_field_with_errors(form.water_ph) }}
    {{ render_field_with_errors(form.water_ec) }}
    {{ render_field_with_errors(form.water_bicarbonates) }}
    {{ render_field_with_errors(form.water_carbonates) }}
    {{ render_field_with_errors(form.water_potasium) }}
    {{ render_field_with_errors(form.water_sulphate) }}
    <input type="submit" class="hoverable waves-effect waves-light btn" value="Add water test!">
  </form>
  <br>
  <a href="{{ url_for('welcome.add_soil_test') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/install_agrisys.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Farm install agrisys
{% endblock %}

{% block install_agrisys_active %}
	active
{% endblock %}

{% block content %}
{#<div class = "container">
    <h4>Install_agrisys</h4>
    <form method="POST" action="{{ url_for('welcome.install_agrisys') }}">
      {{ form.csrf_token }}
      {{ render_field_with_errors(form.agm_lat) }}
      {{ render_field_with_errors(form.agm_lon) }}
      {{ render_field_with_errors(form.ags_lat) }}
      {{ render_field_with_errors(form.ags_lon) }}
      {{ render_field_with_errors(form.agp_lat) }}
      {{ render_field_with_errors(form.agp_lon) }}
      <input type="submit" class="btn btn-primary btn-md" value="Install agrisys!">
    </form>
    <a href="{{ url_for('welcome.add_agrisys') }}" class="btn btn-secondary btn-sm" style="color:black;">Back</a>

  <hr> #}
  <h1>Instructions:</h1>
  <hr>
  <ul>
    <li>1. Go install Agrimodule and Agrisensor where we tell you.</li>
    <li>2. Go plug the Agripump to your farm pump.</li>
  </ul>
	<br>
	<a href="{{ url_for('welcome.add_pump') }}" class="hoverable waves-effect waves-light btn">Next</a>
	<br>
	<br>
	<a href="{{ url_for('welcome.add_agrisys') }}" class="amber darken-1 waves-effect waves-light btn btn-small"><i class="material-icons left">arrow_back</i>Back</a>
</div>
{% endblock content %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/welcome.html
{% extends 'base.html' %}

{% block title %}
	{{ current_user.name }}
{% endblock %}

{% block index_active %}
	active
{% endblock %}

{% block content %}
	<div id = "fh5co-main" class = "container" style = "margin-top: 5%;">
		<div style="padding-left: 2%; text-align: left;">
		    <h1>Welcome</h1>
		    <hr>

			<h1>Hi, {{ current_user.name }} {{ current_user.last_name }}</h1>
			<p>Looks like its your first time here!
			<br>We will guide you through setting up your system in no time.</p>

			{% if set_sys_flag: %}
				<h4>First thing:</h4>
				<label>1. Set up you Agrimodule</label><br>
				<a href="{{ url_for('welcome.add_agrisys') }}" class="hoverable waves-effect waves-light btn">Set up agrimodule</a><br>
			{% else %}
				<h4>Second thing:</h4>
				<label>2. Set up your Farm</label><br>
				<a href="{{ url_for('welcome.add_farm') }}" class="hoverable waves-effect waves-light btn">Set up farm</a><br>
			{% endif %}

		</div>
	</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/welcome_set_farm.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Set farm
{% endblock %}

{% block content %}
<div class = "container">
    <h1>Welcome set farm</h1>
    <hr>
	<h1>Create your farm</h1>
	<form method="POST" action="{{ url_for('welcome.welcome_set_farm') }}">
		{{ form.csrf_token }}
		{{ render_field_with_errors(form.farm_name) }}
		{{ render_field_with_errors(form.farm_location) }}
		{{ render_field_with_errors(form.farm_area) }}
		{{ render_field_with_errors(form.farm_cultivation_process) }}
		<input type="submit" class="btn btn-primary btn-md" value="Create Farm!">
	</form>
</div>
{% endblock %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/welcome_set_field.html
{% extends 'base.html' %}
{% from "_renderfield.html" import render_field, render_field_with_errors %}

{% block title %}
	Set field
{% endblock %}

{# //TODO: datepicker needs to be formated to insert data into db #}

{% block content %}
<div class = "container">
	<h3>Welcome set field</h3>
    <hr>
	<h4>Create a field inside your farm</h4>
	<form method="POST" action="{{ url_for('welcome.welcome_set_field') }}">
		{{ form.csrf_token }}
		{{ render_field_with_errors(form.field_name, placeholder="Plum tomatoes field") }}
		{{ render_field_with_errors(form.field_cultivation_area) }}
		{{ render_field_with_errors(form.field_cultivation_crop) }}
		{{ render_field_with_errors(form.field_cultivation_start_date, class='datepicker') }}
		{{ render_field_with_errors(form.field_cultivation_state) }}
		{{ render_field_with_errors(form.field_cultivation_type) }}
		<input type="submit" class="btn btn-primary btn-md" value="Create Field!">
	</form>
</div>
{% endblock content %}

AgrimoduleSoftware/ASS/ass/solarvibes/welcome/templates/welcome/welcome_set_sys.html
{% extends 'base.html' %}

{% block title %}
	Set System
{% endblock %}

{% block welcome_set_sys_active %}
	active
{% endblock %}

{% block content %}
<div class = "container">
	<h1>Welcome set system</h1>
	<div>
        <hr>
        <h3>We will guide you through the installation of the agrimodule system in four steps.</h3>
        <ul>
          <!-- <li>1. Set the information of your farm. (Name, location, full area and cultivation process of your farm)</li> -->
          <li>1. Connect your application to your agrimodule smart system (Read a QR code)</li>
          <li>2. Install the agrimodule smart system in your farm (Agrimodule, agripump and agrisensor)</li>
          <li>3. Add the pump specs of your farm to your application (Brand, flow rate, head pressure and wattage)</li>
        </ul>
        <a href="{{ url_for('welcome.add_agrisys') }}" class="btn btn-primary">Start</a>
	</div>
</div>
{% endblock content %}